### PR TITLE
fix: create payment link

### LINKED ISSUE #84: Fix Checkout API endpoints

### PR DESCRIPTION
**Pull request by BruceClark406**
Closes #84

### CODE REVIEW

File: lib/src/shared_model/payment_link_related_resources.dart [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+  /// Converts a [Map] to an [PaymentLinkRelatedResources]
+  factory PaymentLinkRelatedResources.fromJson(Map<String, dynamic> json) =>
+      _$PaymentLinkRelatedResourcesFromJson(json);
+
+  /// Converts a [PaymentLinkRelatedResources] to a [Map]
+  Map<String, dynamic> toJson() => _$PaymentLinkRelatedResourcesToJson(this);
+
+  final List<Order> orders;
+  final List<CatalogObject> subscriptionPlans;
```
Comment (mtwichel) [inline lib/src/shared_model/payment_link_related_resources.dart:22]:
```suggestion
  final List<Order>? orders;
  final List<CatalogObject>? subscriptionPlans;
```

File: lib/src/shared_model/payment_link_related_resources.dart [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+import 'package:json_annotation/json_annotation.dart';
+import 'package:square_connect/square_connect.dart';
+
+part 'payment_link_related_resources.g.dart';
+
+@JsonSerializable()
+class PaymentLinkRelatedResources extends Equatable {
+  const PaymentLinkRelatedResources({
+    required this.orders,
+    required this.subscriptionPlans,
```
Comment (mtwichel) [inline lib/src/shared_model/payment_link_related_resources.dart:11]:
```suggestion
   this.orders,
   this.subscriptionPlans,
```

File: pubspec.yaml [hunk 3]
```diff
@@ -1,6 +1,6 @@
 name: square_connect
 description: A wrapper for the Square Connect APIs. It's intended use is in a flutter application to manage inventory, catalog, customers, labor, and more on the Square platform.
-version: 2.0.0-dev.98
+version: 2.0.0-dev.99
```
Comment (mtwichel) [inline pubspec.yaml:3]:
```suggestion
version: 2.0.0-dev.100
```

**Review by mtwichel — CHANGES_REQUESTED** [review]

**Review by mtwichel — APPROVED** [review]
LGTM!
